name-template: "Example title - v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Dependencies"
    labels:
      - "dependencies"
  - title: "Maintenance"
    label: "maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/astrandb/hass_cc_template/v$RESOLVED_VERSION/total.svg)](https://github.com/astrandb/hass_cc_template/releases/v$RESOLVED_VERSION)

  ## Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"
      - ".github/*"
  - label: "bugfix"
    title:
      - "/fix/i"
